# Pod
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: mysql:5
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: fleetman

---
# Service

apiVersion: v1
kind: Service
metadata: 
  name: database
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - name: database-service-port-3306
      protocol: TCP
      port: 3306
      targetPort: 3306