apiVersion: v1
kind: Pod
metadata:
  name: app-fleetman-queue
  labels:
    app: app-fleetman-queue
    release: "1"
spec: 
  containers:
    - image: richardchesterwood/k8s-fleetman-queue:release1
      name: app-fleetman-queue