# Deployment QUEUE

apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
  labels:
    app: queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue
  template: # Template for PODS
    metadata:
      # name: webapp # Now since PODs are managed by ReplicaSet we don't need to mention a name
      labels:
        app: queue
    spec:
      containers:
        - name: webapp
          image: richardchesterwood/k8s-fleetman-queue:release1

---
# Deployment Position Simulator

apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-simulator

spec:
  replicas: 1
  selector:
    matchLabels:
      app: position-simulator

  template:
    metadata:
      labels:
        app: position-simulator
    spec:
      containers:
        - name: webapp
          image: richardchesterwood/k8s-fleetman-position-simulator:release1
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice

