apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  type: NodePort
  selector:
    name: webapp
    release: "0-5"
  
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31231