# Deployment MONGO-DB

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template: # Template for PODS
    metadata:
      # name: webapp # Now since PODs are managed by ReplicaSet we don't need to mention a name
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:3.6.5-jessie
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db # path in container where data is stored
      volumes:
        - name: mongo-persistent-storage
          hostPath:
            path: /mnt/some/directory-structure
            type: DirectoryOrCreate

---
# Services

apiVersion: v1
kind: Service
metadata:
  name: fleetman-mongodb

spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - name: mongoport
      port: 27017
      targetPort: 27017
