# localstorage - mongo-pvc
# WHAT do we want?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
# PersistentVolume : Its used to define whether its a local directory or EBS or Azure
# HOW do we want it implemented?

apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  capcity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/some/new-directory-structure
    type: DirectoryOrCreate

