apiVersion: v1
kind: Service
metadata:
  name: app-fleetman-queue-service
  labels:
    app: app-fleetman-queue
    release: "1"
spec:
  type: NodePort
  selector:
    app: app-fleetman-queue
    release: "1"      
  ports:
    - name: http
      port: 81
      targetPort: 8161
      nodePort: 31232