apiVersion: v1
kind: ConfigMap
metadata: 
  name: global-database-config
  namespace: default

data:
  data.properties: |
    database.url=http://dbserver.somewhere.com:3306
    database.password=P@ssword123