apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: default
data:
  accessKey: bXlBY2Nlc3NLZXkxMjM0 # Key: Value; The value shud be base64 encoded
  secretKey: bXlTZWNyZXQxMjM0